### PR TITLE
Support platform-specific asset configs in react-native.config.js

### PR DESCRIPTION
**Pull request by roryabraham**
Fixes https://github.com/unimonkiez/react-native-asset/issues/34

First-time contributor to this repo, so I'm definitely open to feedback

### CODE REVIEW

**Comment by tobyt42** [comment]
This change would be great to get merged and released.

**Comment by RichardFevrier** [comment]
@unimonkiez would you mind looking at the different proposed pull requests for your project ❤️

**Review by unimonkiez — APPROVED** [review]

**Comment by unimonkiez** [comment]
Available on `v2.1.0`

**Comment by RichardFevrier** [comment]
Thank you a lot 🙏

**Pull request merged**
