### PR TITLE
Update package.json peerDependencies

### PR DESCRIPTION
**Pull request by KBSchmidt**
Solves peer dep issue #32

### CODE REVIEW

**Comment by ziwon-kim-mox** [comment]
Can we merge this in please.

**Comment by Marcuspo** [comment]
+ 1

**Review by trinadhkoyamm — APPROVED** [review]

**Comment by unimonkiez** [comment]
Merging even though not sure why it's a warning... I thought `caret(^)` should still work until `1.0.0`.
Can someone explain this?

**Comment by unimonkiez** [comment]
Available on `v2.1.0`

**Pull request merged**
